### ISSUE TITLE
Convolutional filter size

### ISSUE THREAD

**Issue by tehreemnaqvi** [kyliehuch/DSNN#1]
Hi ,
I am following your code. In your MNIST code, you kept kernel size = 2 in second conv layer.
Can you please explain how did you keep kernel size =2 because we normally define filter size = 3,5, 7, etc.

Thanks

**Comment by kyliehuch** [comment]
Hello! Sorry for the delayed response - this is no longer an active project. As stated in the readme, I did not write the DSNNs, they are from the papers linked in the readme; please open this issue in the author's repo: https://github.com/miladmozafari/SpykeTorch. The code in this repo is intended to extract and visualize the weight distributions of DSNNs built using the SpykeTorch tool.
